version: '3.6'
services:
  api:
    container_name: listedkit-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      APP_ENV: development
      NODE_ENV: development
    volumes:
      - ./api/src:/app/src
    networks:
      - listedkit
    ports:
      - 3001:3001
  web:
    container_name: listedkit-web
    build:
      context: ./b2b-onboarding-supabase
      dockerfile: Dockerfile.dev
      args:
        APP_ENV: development
        NODE_ENV: development
    volumes:
      - ./b2b-onboarding-supabase/src:/app/src
    networks:
      - listedkit
    ports:
      - 3002:3002

networks:
  listedkit:
    name: listedkit-network
