version: '3.6'
services:
  web:
    build:
      context: ./b2b-onboarding
      dockerfile: Dockerfile.dev
      args:
        APP_ENV: development
        NODE_ENV: development
    volumes:
      - .b2b-onboarding/src:/app/src
    networks:
      - ship
    ports:
      - "3002:3002"

networks:
  ship:
    name: ship_network
