FROM node:16.13.1

EXPOSE 3001

ARG NODE_ENV
ARG APP_ENV

ENV NODE_ENV=$NODE_ENV
ENV APP_ENV=$APP_ENV

WORKDIR /app
COPY ["./package.json", "package-lock.json", "./.npmrc", "./.eslintrc.js", "./tsconfig.json", "/app/"]
RUN npm ci --quiet

COPY . ./

RUN npm run build:tcs

CMD npm run development
